<template>
  <div style="padding: 2rem; max-width: 800px; margin: 0 auto;">
    <h1>ISR Test Page</h1>
    <p>This page uses ISR (Incremental Static Regeneration)</p>
    
    <div style="background: #f5f5f5; padding: 1rem; border-radius: 8px; margin: 1rem 0;">
      <h2>Data from API:</h2>
      <div v-if="pending">Loading...</div>
      <div v-else-if="data">
        <p><strong>Timestamp:</strong> {{ data.timestamp }}</p>
        <p><strong>Message:</strong> {{ data.message }}</p>
        <p><strong>Generated At:</strong> {{ data.generatedAt }}</p>
      </div>
      <div v-else>No data available</div>
    </div>
    
    <div style="background: #e3f2fd; padding: 1rem; border-radius: 8px; margin: 1rem 0;">
      <h3>How ISR Works:</h3>
      <ul>
        <li>First request: Page is generated by serverless function</li>
        <li>Subsequent requests: Served from CDN cache</li>
        <li>After cache expires (1 hour): Page regenerates on next request</li>
        <li><strong>On-demand revalidation:</strong> Click "Revalidate Cache" to immediately regenerate</li>
      </ul>
    </div>
    
    <div style="display: flex; gap: 1rem; margin-top: 1rem;">
      <button @click="refresh()" style="padding: 0.5rem 1rem; background: #1976d2; color: white; border: none; border-radius: 4px; cursor: pointer;">
        Refresh Data (Client-side)
      </button>
      <button @click="revalidate()" style="padding: 0.5rem 1rem; background: #d32f2f; color: white; border: none; border-radius: 4px; cursor: pointer;">
        Revalidate Cache (On-demand)
      </button>
    </div>
    
    <div v-if="revalidateStatus" style="margin-top: 1rem; padding: 1rem; background: #fff3cd; border-radius: 4px;">
      <p><strong>Revalidation Status:</strong> {{ revalidateStatus }}</p>
    </div>
  </div>
</template>

<script setup>
import { setResponseHeader } from 'h3'

// Set cache tag directly on the page (as per article)
const event = useRequestEvent()
if (import.meta.server && event) {
  setResponseHeader(event, 'netlify-cache-tag', 'test-isr')
}

// Simple data fetch - no await to prevent blocking
const { data, refresh, pending } = useFetch('/api/test-isr')

// Revalidation status
const revalidateStatus = ref('')

// On-demand revalidation function
async function revalidate() {
  revalidateStatus.value = 'Purging cache...'
  
  try {
    // Use the revalidate endpoint from netlify/functions/revalidate.js
    const response = await $fetch('/.netlify/functions/revalidate?tag=test-isr', {
      method: 'GET'
    })
    
    revalidateStatus.value = 'Cache purged! Reload the page to see new data.'
    setTimeout(() => {
      window.location.reload()
    }, 1000)
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Failed to revalidate'
    revalidateStatus.value = 'Error: ' + errorMessage
    console.error('Revalidation error:', error)
  }
}

// SEO
useSeoMeta({
  title: 'ISR Test Page',
  description: 'Testing Incremental Static Regeneration with Nuxt 4'
})
</script>

